# Generated by Django 3.2 on 2021-04-16 13:41

from django.db import migrations, models
import django.db.models.deletion
import lightning_plus.api_basebone.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100, unique=True, verbose_name='模型名称')),
                ('config', lightning_plus.api_basebone.core.fields.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Admin配置',
                'verbose_name_plural': 'Admin配置',
            },
        ),
        migrations.CreateModel(
            name='FieldAdmin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=150, verbose_name='字段名')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsm_config.admin', verbose_name='关联Admin')),
            ],
            options={
                'verbose_name': 'Admin字段配置',
                'verbose_name_plural': 'Admin字段配置',
                'unique_together': {('admin', 'field')},
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.JSONField(null=True, verbose_name='配置值')),
            ],
            options={
                'verbose_name': '网站配置',
                'verbose_name_plural': '网站配置',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='名称')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='图标')),
                ('page', models.CharField(choices=[['list', '列表页'], ['detail', '详情页'], ['adminConfig', '页面配置面板'], ['auto', '自定义页面'], ['iframe', 'Iframe页面']], default='', help_text='前端功能页面的标识', max_length=200, null=True, verbose_name='页面类型')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义路径')),
                ('permission', models.CharField(blank=True, help_text='格式有<app_label>.<codename>', max_length=200, null=True, verbose_name='关联权限')),
                ('model', models.CharField(max_length=200, null=True, verbose_name='关联模型')),
                ('sequence', models.IntegerField(default=1000, help_text='数值越小，排列越前', verbose_name='排序')),
                ('type', models.CharField(choices=[('item', '菜单项'), ('group', '菜单组')], default='item', max_length=20, verbose_name='菜单类型')),
                ('groups', models.ManyToManyField(blank=True, help_text='限制可查看此菜单的角色，留空则不限制', related_name='menus', to='auth.Group', verbose_name='可见角色')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='bsm_config.menu', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '导航菜单',
                'verbose_name_plural': '导航菜单',
            },
        ),
        migrations.CreateModel(
            name='FieldPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('read', models.BooleanField(default=True, verbose_name='读')),
                ('write', models.BooleanField(default=True, verbose_name='写')),
                ('field_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsm_config.fieldadmin', verbose_name='关联字段')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='角色')),
            ],
            options={
                'verbose_name': '字段权限配置',
                'verbose_name_plural': '字段权限配置',
                'unique_together': {('field_admin', 'group')},
            },
        ),
    ]
