# Generated by Django 3.2 on 2021-04-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bsm_config", "0033_auto_20201203_1558"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="fieldadmin",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="fieldpermission",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="menu",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="setting",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
