# Generated by Django 3.2 on 2021-04-15 22:21

from django.db import migrations
import lightning_plus.api_basebone.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("bsm_config", "0034_auto_20210415_2203"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="config",
            field=lightning_plus.api_basebone.core.fields.JSONField(default=dict),
        ),
    ]
