# Generated by Django 3.2 on 2021-04-16 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lightning_plus.api_basebone.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('action', models.CharField(blank=True, default='', max_length=20, verbose_name='动作')),
                ('app_label', models.CharField(blank=True, default='', max_length=20, verbose_name='应用标识')),
                ('model_slug', models.CharField(blank=True, default='', max_length=30, verbose_name='模型标识')),
                ('object_id', models.CharField(blank=True, default='', max_length=20, verbose_name='数据ID')),
                ('message', models.CharField(blank=True, default='', max_length=50, verbose_name='消息')),
                ('params', lightning_plus.api_basebone.core.fields.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '动作日志记录',
                'verbose_name_plural': '动作日志记录',
            },
        ),
    ]
