# Generated by Django 3.2 on 2021-04-15 22:03

from django.db import migrations, models
import lightning_plus.api_basebone.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api_basebone", "0017_auto_20191101_1829"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminlog",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="adminlog",
            name="params",
            field=lightning_plus.api_basebone.core.fields.JSONField(default=dict),
        ),
    ]
