# Generated by Django 3.2 on 2021-04-16 13:41

from django.db import migrations, models
import django.db.models.deletion
import lightning_plus.puzzle.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.SlugField(default=lightning_plus.puzzle.models.uuid4_hex, primary_key=True, serialize=False, unique=True, verbose_name='标识')),
                ('component', models.CharField(default='', max_length=20, verbose_name='组件')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='puzzle.block', verbose_name='父结点')),
            ],
            options={
                'verbose_name': '渲染块',
                'verbose_name_plural': '渲染块',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzle.block', verbose_name='根结点')),
            ],
            options={
                'verbose_name': '页面',
                'verbose_name_plural': '页面',
            },
        ),
    ]
