# Generated by Django 3.2 on 2021-04-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shield", "0002_rule_combinator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condition",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="rule",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
